# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diy.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DiyScreen(object):
    def setupUi(self, DiyScreen):
        DiyScreen.setObjectName(_fromUtf8("DiyScreen"))
        DiyScreen.resize(917, 622)
        self.verticalLayout = QtGui.QVBoxLayout(DiyScreen)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(DiyScreen)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(26)
        font.setKerning(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(18)
        font.setKerning(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.list_booze = QtGui.QListWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(16)
        self.list_booze.setFont(font)
        self.list_booze.setObjectName(_fromUtf8("list_booze"))
        self.verticalLayout_2.addWidget(self.list_booze)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.list_soda = QtGui.QListWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(16)
        self.list_soda.setFont(font)
        self.list_soda.setObjectName(_fromUtf8("list_soda"))
        self.verticalLayout_3.addWidget(self.list_soda)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.list_extraTouch = QtGui.QListWidget(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(16)
        self.list_extraTouch.setFont(font)
        self.list_extraTouch.setObjectName(_fromUtf8("list_extraTouch"))
        self.verticalLayout_4.addWidget(self.list_extraTouch)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_booze = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_booze.sizePolicy().hasHeightForWidth())
        self.label_booze.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(20)
        self.label_booze.setFont(font)
        self.label_booze.setText(_fromUtf8(""))
        self.label_booze.setObjectName(_fromUtf8("label_booze"))
        self.horizontalLayout_2.addWidget(self.label_booze)
        self.label_plus2 = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plus2.sizePolicy().hasHeightForWidth())
        self.label_plus2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        self.label_plus2.setFont(font)
        self.label_plus2.setObjectName(_fromUtf8("label_plus2"))
        self.horizontalLayout_2.addWidget(self.label_plus2)
        self.label_soda = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_soda.sizePolicy().hasHeightForWidth())
        self.label_soda.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(20)
        self.label_soda.setFont(font)
        self.label_soda.setText(_fromUtf8(""))
        self.label_soda.setObjectName(_fromUtf8("label_soda"))
        self.horizontalLayout_2.addWidget(self.label_soda)
        self.label_plus1 = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_plus1.sizePolicy().hasHeightForWidth())
        self.label_plus1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(18)
        self.label_plus1.setFont(font)
        self.label_plus1.setObjectName(_fromUtf8("label_plus1"))
        self.horizontalLayout_2.addWidget(self.label_plus1)
        self.label_extraTouch = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_extraTouch.sizePolicy().hasHeightForWidth())
        self.label_extraTouch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(20)
        self.label_extraTouch.setFont(font)
        self.label_extraTouch.setText(_fromUtf8(""))
        self.label_extraTouch.setObjectName(_fromUtf8("label_extraTouch"))
        self.horizontalLayout_2.addWidget(self.label_extraTouch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_drink = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_drink.sizePolicy().hasHeightForWidth())
        self.label_drink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(24)
        self.label_drink.setFont(font)
        self.label_drink.setText(_fromUtf8(""))
        self.label_drink.setObjectName(_fromUtf8("label_drink"))
        self.horizontalLayout.addWidget(self.label_drink)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.level_alcohol = QtGui.QSlider(DiyScreen)
        self.level_alcohol.setOrientation(QtCore.Qt.Horizontal)
        self.level_alcohol.setObjectName(_fromUtf8("level_alcohol"))
        self.verticalLayout_5.addWidget(self.level_alcohol)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_pussy = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pussy.sizePolicy().hasHeightForWidth())
        self.label_pussy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(14)
        self.label_pussy.setFont(font)
        self.label_pussy.setObjectName(_fromUtf8("label_pussy"))
        self.horizontalLayout_6.addWidget(self.label_pussy)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_brave = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_brave.sizePolicy().hasHeightForWidth())
        self.label_brave.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(14)
        self.label_brave.setFont(font)
        self.label_brave.setObjectName(_fromUtf8("label_brave"))
        self.horizontalLayout_6.addWidget(self.label_brave)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_viking = QtGui.QLabel(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_viking.sizePolicy().hasHeightForWidth())
        self.label_viking.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(18)
        self.label_viking.setFont(font)
        self.label_viking.setObjectName(_fromUtf8("label_viking"))
        self.horizontalLayout_6.addWidget(self.label_viking)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.pb_back = QtGui.QPushButton(DiyScreen)
        self.pb_back.setText(_fromUtf8(""))
        self.pb_back.setObjectName(_fromUtf8("pb_back"))
        self.horizontalLayout_5.addWidget(self.pb_back)
        self.pb_makeDrink = QtGui.QPushButton(DiyScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_makeDrink.sizePolicy().hasHeightForWidth())
        self.pb_makeDrink.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(36)
        self.pb_makeDrink.setFont(font)
        self.pb_makeDrink.setDefault(True)
        self.pb_makeDrink.setObjectName(_fromUtf8("pb_makeDrink"))
        self.horizontalLayout_5.addWidget(self.pb_makeDrink)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(DiyScreen)
        QtCore.QMetaObject.connectSlotsByName(DiyScreen)

    def retranslateUi(self, DiyScreen):
        DiyScreen.setWindowTitle(_translate("DiyScreen", "Do It Yourself!", None))
        self.groupBox.setTitle(_translate("DiyScreen", "Do It Yourself!", None))
        self.groupBox_3.setTitle(_translate("DiyScreen", "Booze", None))
        self.groupBox_2.setTitle(_translate("DiyScreen", "Soda", None))
        self.groupBox_4.setTitle(_translate("DiyScreen", "Extra Touch", None))
        self.label_plus2.setText(_translate("DiyScreen", "+", None))
        self.label_plus1.setText(_translate("DiyScreen", "+", None))
        self.label_pussy.setText(_translate("DiyScreen", "Pussy...", None))
        self.label_brave.setText(_translate("DiyScreen", "Brave enough", None))
        self.label_viking.setText(_translate("DiyScreen", "Viking!", None))
        self.pb_makeDrink.setText(_translate("DiyScreen", "Create!", None))

