# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Positioning.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Positioning(object):
    def setupUi(self, Positioning):
        Positioning.setObjectName(_fromUtf8("Positioning"))
        Positioning.resize(934, 695)
        self.verticalLayout = QtGui.QVBoxLayout(Positioning)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pb_exit = QtGui.QPushButton(Positioning)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pb_exit.setFont(font)
        self.pb_exit.setObjectName(_fromUtf8("pb_exit"))
        self.horizontalLayout_4.addWidget(self.pb_exit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_bottleName = QtGui.QLabel(Positioning)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_bottleName.setFont(font)
        self.label_bottleName.setText(_fromUtf8(""))
        self.label_bottleName.setObjectName(_fromUtf8("label_bottleName"))
        self.horizontalLayout_4.addWidget(self.label_bottleName)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pb_home = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_home.sizePolicy().hasHeightForWidth())
        self.pb_home.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pb_home.setFont(font)
        self.pb_home.setObjectName(_fromUtf8("pb_home"))
        self.horizontalLayout_4.addWidget(self.pb_home)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pb_higher = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_higher.sizePolicy().hasHeightForWidth())
        self.pb_higher.setSizePolicy(sizePolicy)
        self.pb_higher.setText(_fromUtf8(""))
        self.pb_higher.setObjectName(_fromUtf8("pb_higher"))
        self.horizontalLayout_10.addWidget(self.pb_higher)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pb_lower = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_lower.sizePolicy().hasHeightForWidth())
        self.pb_lower.setSizePolicy(sizePolicy)
        self.pb_lower.setText(_fromUtf8(""))
        self.pb_lower.setObjectName(_fromUtf8("pb_lower"))
        self.horizontalLayout_11.addWidget(self.pb_lower)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pb_right = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_right.sizePolicy().hasHeightForWidth())
        self.pb_right.setSizePolicy(sizePolicy)
        self.pb_right.setText(_fromUtf8(""))
        self.pb_right.setObjectName(_fromUtf8("pb_right"))
        self.gridLayout.addWidget(self.pb_right, 2, 3, 1, 1)
        self.pb_fastLeft = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_fastLeft.sizePolicy().hasHeightForWidth())
        self.pb_fastLeft.setSizePolicy(sizePolicy)
        self.pb_fastLeft.setText(_fromUtf8(""))
        self.pb_fastLeft.setObjectName(_fromUtf8("pb_fastLeft"))
        self.gridLayout.addWidget(self.pb_fastLeft, 2, 0, 1, 1)
        self.pb_down = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_down.sizePolicy().hasHeightForWidth())
        self.pb_down.setSizePolicy(sizePolicy)
        self.pb_down.setText(_fromUtf8(""))
        self.pb_down.setObjectName(_fromUtf8("pb_down"))
        self.gridLayout.addWidget(self.pb_down, 3, 2, 1, 1)
        self.pb_fastDown = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_fastDown.sizePolicy().hasHeightForWidth())
        self.pb_fastDown.setSizePolicy(sizePolicy)
        self.pb_fastDown.setText(_fromUtf8(""))
        self.pb_fastDown.setObjectName(_fromUtf8("pb_fastDown"))
        self.gridLayout.addWidget(self.pb_fastDown, 4, 2, 1, 1)
        self.pb_up = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_up.sizePolicy().hasHeightForWidth())
        self.pb_up.setSizePolicy(sizePolicy)
        self.pb_up.setText(_fromUtf8(""))
        self.pb_up.setObjectName(_fromUtf8("pb_up"))
        self.gridLayout.addWidget(self.pb_up, 1, 2, 1, 1)
        self.pb_fastUp = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_fastUp.sizePolicy().hasHeightForWidth())
        self.pb_fastUp.setSizePolicy(sizePolicy)
        self.pb_fastUp.setText(_fromUtf8(""))
        self.pb_fastUp.setObjectName(_fromUtf8("pb_fastUp"))
        self.gridLayout.addWidget(self.pb_fastUp, 0, 2, 1, 1)
        self.pb_left = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_left.sizePolicy().hasHeightForWidth())
        self.pb_left.setSizePolicy(sizePolicy)
        self.pb_left.setText(_fromUtf8(""))
        self.pb_left.setObjectName(_fromUtf8("pb_left"))
        self.gridLayout.addWidget(self.pb_left, 2, 1, 1, 1)
        self.pb_fastRight = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_fastRight.sizePolicy().hasHeightForWidth())
        self.pb_fastRight.setSizePolicy(sizePolicy)
        self.pb_fastRight.setText(_fromUtf8(""))
        self.pb_fastRight.setObjectName(_fromUtf8("pb_fastRight"))
        self.gridLayout.addWidget(self.pb_fastRight, 2, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(64, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.label_x = QtGui.QLabel(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_x.sizePolicy().hasHeightForWidth())
        self.label_x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(28)
        self.label_x.setFont(font)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.horizontalLayout_2.addWidget(self.label_x)
        self.txt_x = QtGui.QLineEdit(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_x.sizePolicy().hasHeightForWidth())
        self.txt_x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_x.setFont(font)
        self.txt_x.setObjectName(_fromUtf8("txt_x"))
        self.horizontalLayout_2.addWidget(self.txt_x)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.label_y = QtGui.QLabel(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_y.sizePolicy().hasHeightForWidth())
        self.label_y.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(28)
        self.label_y.setFont(font)
        self.label_y.setObjectName(_fromUtf8("label_y"))
        self.horizontalLayout_2.addWidget(self.label_y)
        self.txt_y = QtGui.QLineEdit(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_y.sizePolicy().hasHeightForWidth())
        self.txt_y.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_y.setFont(font)
        self.txt_y.setObjectName(_fromUtf8("txt_y"))
        self.horizontalLayout_2.addWidget(self.txt_y)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.label_z = QtGui.QLabel(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_z.sizePolicy().hasHeightForWidth())
        self.label_z.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Single Sleeve"))
        font.setPointSize(28)
        self.label_z.setFont(font)
        self.label_z.setObjectName(_fromUtf8("label_z"))
        self.horizontalLayout_3.addWidget(self.label_z)
        self.txt_z = QtGui.QLineEdit(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_z.sizePolicy().hasHeightForWidth())
        self.txt_z.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_z.setFont(font)
        self.txt_z.setObjectName(_fromUtf8("txt_z"))
        self.horizontalLayout_3.addWidget(self.txt_z)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pb_setTop = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_setTop.sizePolicy().hasHeightForWidth())
        self.pb_setTop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pb_setTop.setFont(font)
        self.pb_setTop.setObjectName(_fromUtf8("pb_setTop"))
        self.horizontalLayout.addWidget(self.pb_setTop)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.pb_setBottom = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_setBottom.sizePolicy().hasHeightForWidth())
        self.pb_setBottom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pb_setBottom.setFont(font)
        self.pb_setBottom.setObjectName(_fromUtf8("pb_setBottom"))
        self.horizontalLayout.addWidget(self.pb_setBottom)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.pb_finish = QtGui.QPushButton(Positioning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_finish.sizePolicy().hasHeightForWidth())
        self.pb_finish.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pb_finish.setFont(font)
        self.pb_finish.setObjectName(_fromUtf8("pb_finish"))
        self.horizontalLayout.addWidget(self.pb_finish)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Positioning)
        QtCore.QMetaObject.connectSlotsByName(Positioning)

    def retranslateUi(self, Positioning):
        Positioning.setWindowTitle(_translate("Positioning", "Form", None))
        self.pb_exit.setText(_translate("Positioning", "Back", None))
        self.pb_home.setText(_translate("Positioning", "Home", None))
        self.label_x.setText(_translate("Positioning", "X:", None))
        self.label_y.setText(_translate("Positioning", "Y:", None))
        self.label_z.setText(_translate("Positioning", "Z:", None))
        self.pb_setTop.setText(_translate("Positioning", "Set Bottle Top", None))
        self.pb_setBottom.setText(_translate("Positioning", "Set Bottle Bottom", None))
        self.pb_finish.setText(_translate("Positioning", "Finish!", None))

